import numpy as np
arr=np.array(['pens','apps','cell'])
print(arr.dtype)
arr1=np.array([1,2,3,4,5])
print(arr1.dtype)
arr2=np.array([3,4,1,5],dtype='i4')
print(arr2.dtype)
arr3=np.array([1,2,3,4,],dtype='S')
print(arr3)
print(arr3.dtype)